### PR TITLE
Support for Django 2.0, 2.1 & 2.2

### PR DESCRIPTION
**Pull request by joehybird**
Based on work of @adamchainz for django 2.1 (see #32)

### CODE REVIEW

**Comment by hsmett** [comment]
👍

**Comment by adamchainz** [comment]
LGTM. What I said in #32 still stands, happy to help maintain.

**Comment by mrjmad** [comment]
:+1:

**Comment by selwin** [comment]
Sorry for merging this in so late. I don't get PR notifications in my mail until someone mentions my name.

**Comment by adamchainz** [comment]
Thanks!

**Pull request merged**
